FROM javidr/yasca_base:latest
ARG zasca_version
COPY dist/zasca-$zasca_version-py3-none-any.whl .
RUN pip install zasca-$zasca_version-py3-none-any.whl && rm zasca-$zasca_version-py3-none-any.whl
COPY entrypoint.sh .
ENTRYPOINT ["/bin/sh","/entrypoint.sh"]
